"""Utilities for exact simplicial-complex shape calculations."""

from __future__ import annotations

import math
from collections import defaultdict
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable


@dataclass(frozen=True)
class SimplicialClosureShape:
    """Shape metadata for the downward closure generated by facets."""

    active_vertices: int
    maximal_simplices: int
    shape: list[str]
    total_simplices: str


def _maximal_facets(facets: Iterable[frozenset[int]]) -> list[frozenset[int]]:
    """Return unique facets that are not contained in another facet."""
    maximal: list[frozenset[int]] = []

    for facet in sorted(
        set(facets),
        key=lambda current_facet: (len(current_facet), tuple(sorted(current_facet))),
        reverse=True,
    ):
        if len(facet) == 0:
            continue
        if not any(facet <= existing_facet for existing_facet in maximal):
            maximal.append(facet)

    return maximal


def compute_simplicial_closure_shape(
    facets: Iterable[Iterable[int]],
    *,
    num_vertices: int,
) -> SimplicialClosureShape:
    """Compute the exact f-vector of the simplicial closure generated by facets.

    The returned 0-simplex count is ``num_vertices`` so explicitly declared isolated
    vertices are retained. Higher-dimensional counts are derived from the union of
    all nonempty subsets contained in at least one maximal facet.
    """
    facet_sets = [frozenset(facet) for facet in facets]
    active_vertices = len(set().union(*facet_sets)) if facet_sets else 0
    maximal_facets = _maximal_facets(facet_sets)

    coefficients: dict[frozenset[int], int] = {}
    for facet in maximal_facets:
        updates: defaultdict[frozenset[int], int] = defaultdict(int)
        updates[facet] += 1

        for intersection_set, coefficient in coefficients.items():
            intersection = intersection_set & facet
            if intersection:
                updates[intersection] -= coefficient

        for intersection_set, coefficient in updates.items():
            if coefficient == 0:
                continue
            coefficients[intersection_set] = (
                coefficients.get(intersection_set, 0) + coefficient
            )
            if coefficients[intersection_set] == 0:
                del coefficients[intersection_set]

    max_size = max((len(facet) for facet in maximal_facets), default=1)
    shape = [num_vertices]
    for simplex_size in range(2, max_size + 1):
        simplex_count = sum(
            coefficient * math.comb(len(intersection_set), simplex_size)
            for intersection_set, coefficient in coefficients.items()
            if len(intersection_set) >= simplex_size
        )
        shape.append(simplex_count)

    return SimplicialClosureShape(
        active_vertices=active_vertices,
        maximal_simplices=len(maximal_facets),
        shape=[str(count) for count in shape],
        total_simplices=str(sum(shape)),
    )
