import type { Metadata } from "next";
import "./globals.css";

import Footer from "../components/footer";
import Navbar from "../components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-static";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="mx-auto max-w-7xl px-6 py-12">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
